### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by adamthesax** [elijahmanor/scss-lint-loader#1]
Hi-

What's the current status of this project. Definitely seems like a handy loader for our webpack build. Is it near release? If so when do you think it'll be published to NPM?

Thanks!

**Comment by saulhardman** [comment]
:+1: for NPM publish.

**Comment by elijahmanor** [comment]
Just published the loader to npm https://www.npmjs.com/package/scss-lint-loader

I created it on a plane trip to Australia without wifi, so it was pretty barebones. 

We just switched our grunt/browserify build over to webpack and I'm pulling in this preloader into our project now. I've already encountered some issues, but plan to address them to fit our needs. 

Thanks for your interest.
